# 低軌衛星 SDN 網路模擬配置
# LEO Satellite SDN Network Simulation Configuration

# 控制器配置
controller:
  ip: "192.168.1.101"
  port: 6653
  ngrok: "23f6-101-3-154-122.ngrok-free.app"
  
# 衛星配置
satellites:
  count: 2                    # 初始衛星數量（簡化為2顆）
  altitude: 550               # 軌道高度 (km)
  inclination: 53             # 軌道傾角 (度)
  orbital_period: 5760        # 軌道週期 (秒，約96分鐘)
  
# 地面站配置
ground_stations:
  min_elevation_angle: 10     # 最小仰角 (度)
  detection_range: 1000       # 偵測範圍 (km)
  locations:
    - name: "taipei"
      latitude: 25.0330
      longitude: 121.5654
    - name: "tokyo"  
      latitude: 35.6762
      longitude: 139.6503
    - name: "seoul"
      latitude: 37.5665
      longitude: 126.9780
    - name: "singapore"
      latitude: 1.3521
      longitude: 103.8198

# 網路配置
network:
  update_interval: 30         # 位置更新間隔 (秒)
  link_bandwidth: 10          # 預設鏈路頻寬 (Mbps)
  link_delay: "20ms"          # 預設鏈路延遲
  isl_bandwidth: 100          # 衛星間鏈路頻寬 (Mbps)
  isl_delay: "5ms"            # 衛星間鏈路延遲

# QoS 配置
qos:
  enable: true
  priority_levels: 3
  bandwidth_classes:
    - name: "high"
      bandwidth: 50
    - name: "medium" 
      bandwidth: 20
    - name: "low"
      bandwidth: 5
